### ISSUE TITLE
Creating an express server.

### ISSUE THREAD

**Issue by Necrocryosis** [VishalHaswani/password-managment-system-browser-extention#5]
Creating a Express.js server using Typscript.

Uses:
1. Authentication of User
2. CRUD Operations for authenticated user.

**Comment by VishalHaswani** [comment]
We should use `ts-node` to improve the developer experience.
Reference: [Set up Node.js project with Typescript, ESLint, and Prettier](https://blog.tericcabrel.com/set-up-a-nodejs-project-with-typescript-eslint-and-prettier/)

**Comment by VishalHaswani** [comment]
@Necrocryosis I have made changes to the repo, please pull the changes, check them once and raise a PR if everything looks good.
